# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
  disable:
    - typecheck  # Disabled due to Go toolchain version mismatch in dependencies

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: false
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/yourusername/go-historical-data
  
  misspell:
    locale: US
  
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (too noisy)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    # Exclude known issues in vendor/
    - path: vendor/
      linters:
        - all

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true