# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # includes gosimple and unused in v2.x
    - misspell
    - unconvert
    - unparam
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  misspell:
    locale: US
  
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (too noisy)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  
  # Exclude directories from linting
  exclude-dirs:
    - vendor
    - bin
    - .gomodcache
    - .gocache
  exclude-dirs-use-default: true
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    # Exclude generated files
    - path: .*_gen\.go
      linters:
        - all
    - path: .*\.pb\.go
      linters:
        - all
    - path: .*\.pb\.gw\.go
      linters:
        - all
    
    # Exclude known issues in vendor/
    - path: vendor/
      linters:
        - all
    
    # Exclude third-party code in Go module cache
    - path: .*/go/pkg/mod/.*
      linters:
        - all

output:
  formats:
    - colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true