app:
  env: staging
  name: historical-data-api
  port: 8080
  debug: false

database:
  host: ${DB_HOST}
  port: 3306
  name: historical_data
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

api:
  rate_limit: 500
  request_timeout: 30
  shutdown_timeout: 30

logging:
  level: info
  format: json
  logstash_host: logstash
  logstash_port: 5044
  enable_logstash: true

cors:
  allowed_origins:
    - "https://staging.example.com"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - "*"

tracing:
  enabled: true
  service_name: historical-data-api
  service_version: 1.0.0
  jaeger_endpoint: jaeger:4318
  sampling_rate: 0.5

