app:
  env: development
  name: historical-data-api
  port: 8080
  debug: true

database:
  host: localhost
  port: 3306
  name: historical_data
  user: root
  password: root_password
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

api:
  rate_limit: 100
  request_timeout: 30
  shutdown_timeout: 30

logging:
  level: debug
  format: json

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - "*"

tracing:
  enabled: true
  service_name: historical-data-api
  service_version: 1.0.0
  jaeger_endpoint: jaeger:4318
  sampling_rate: 1.0

