# Prometheus configuration for Historical Data API
global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  scrape_timeout: 10s # Timeout after 10 seconds
  external_labels:
    cluster: 'historical-data-api'
    environment: 'development'

# Alertmanager configuration (optional, uncomment when needed)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: 'prometheus'

  # Historical Data API
  - job_name: 'historical-data-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8080']
        labels:
          app: 'historical-data-api'
          service: 'api'
          environment: 'dev'

  # MySQL Exporter (optional, if you add mysql-exporter container)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
  #       labels:
  #         app: 'mysql'

  # Node Exporter (optional, for host metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         app: 'node-exporter'

