apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    isDefault: false
    editable: true
    jsonData:
      tracesToMetrics:
        # This enables correlation between traces and metrics
        datasourceUid: 'prometheus'
        tags: [{ key: 'service', value: 'service_name' }]
      nodeGraph:
        enabled: true
      spanBar:
        type: 'Tag'
        tag: 'http.method'

